services:
  - type: web
    name: bsc-inspection-server
    runtime: node
    region: singapore
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: TENANT_ID
        sync: false
      - key: USER_ID
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SETUP_KEY
        sync: false
